[tools]
node = "23.5.0"
"npm:wrangler" = "3.111.0"
pnpm = "9.15.1"

[tasks]
dev = "astro dev"
start = "astro dev"
build = "astro check && astro build"
preview = "astro preview"
astro = "astro"
upgrade-astro = "pnpm dlx @astrojs/upgrade"

[env]
_.path = ["node_modules/.bin"]
