[tools]
pnpm = "10.12.4"

[env]
_.path = "node_modules/.bin"

[settings]
# Node version is managed in .node-version
# This is to ensure that the correct node version is during cloudflare build
idiomatic_version_file_enable_tools = ["node"]

[tasks.upload-assets]
description = "Upload assets to Cloudflare R2. Run with `-- --force` to force upload."
run = "tsx scripts/upload-assets.ts"

[tasks.download-assets]
run = "tsx scripts/download-assets.ts"

[tasks.dev]
run = "pnpm run dev"

[tasks.fmt]
run = "biome check --write --unsafe ."

[tasks."check:types"]
run = "tsc --noEmit"

[tasks."check:format"]
run = "biome check ."

[tasks.check]
depends = "check:*"

[tasks."gen:better-auth"]
run = "pnpm dlx @better-auth/cli@latest generate"
