[tools]
pnpm = "9.15.1"

[env]
_.path = "node_modules/.bin"

[settings]
# Node version is managed in .node-version
# This is to ensure that the correct node version is during cloudflare build
idiomatic_version_file_enable_tools = ["node"]
