[tools]
pnpm = "10.11.0"

[env]
_.path = "node_modules/.bin"

[settings]
# Node version is managed in .node-version
# This is to ensure that the correct node version is during cloudflare build
idiomatic_version_file_enable_tools = ["node"]

[tasks.upload-assets]
description = "Upload assets to Cloudflare R2. Run with `-- --force` to force upload."
run = "tsx scripts/upload-assets.ts"

[tasks.download-assets]
run = "tsx scripts/download-assets.ts"

[tasks.dev]
run = "pnpm run dev"
